version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: /home/fabiano/front_chat_lab
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development